stages:
  - test

run_cicd_test:
  stage: test
  image: lxeu/devops-build-image:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  script:
    - if [ ! -z $CICD_DEBUG_CATCH ]; then tail -f /dev/null ; fi
    - bash ./cicd cicd_test