#!/bin/bash

# Linuxengineerings lxe helper script
# Used to wrap custom callable cli functions inside one script
############################# RH helper functions ##############################

HELPER_ROOT=$(dirname $(readlink -f $0))

# Uncomment if your script should run in the directory this script is located.

source ${HELPER_ROOT}/lib.hd

list_units()
{
	_rh_try_ret_help 'List units'
	find ${HELPER_ROOT}/units/ | grep -oP "(?<=units/)(.*)(?=/u.hd$)"

	if [ -d "${HOME}/.lxe/hd/units" ]
	then
		echo ""
		echo "Custom units in ~/.lxe/hd/units:"
		find ${HOME}/.lxe/hd/units | grep -oP "(?<=units/)(.*)(?=/u.hd$)"
	fi
}

u()
{
	_rh_try_ret_help 'Run unit file'
	unit="${HELPER_ROOT}/units/$1/u.hd"
	HD_UNIT_DIR="${HELPER_ROOT}/units/$1"

	if [ -e "${HOME}/.lxe/hd/units/$1/u.hd" ]
	then
		unit="${HOME}/.lxe/hd/units/$1/u.hd"
		HD_UNIT_DIR="${HOME}/.lxe/hd/units/$1"
	fi

	if [ ! -e "$unit" ]
	then
		echo "Unit \"$1\" does not exists"
		echo ""
		echo "Available units:"
		list_units
		exit 1
	fi
	shift

	source $unit
	lxe_launch_helper "$@"
}


_rh_try_ret_help()
{
	if [ ! -z $RH_RUNTIME_REQUEST_HELP ]
	then
		echo $1
		exit 1;
	fi
}

############################ RH built-in functions #############################

help()
{
	_rh_try_ret_help "Prints help with the list of all annotated functions"

cat <<EOF
Linuxengineering helper script.
This is a wrapper script that lets you collect functions for CLI use.
Specify one function from the following:
EOF
	RH_RUNTIME_REQUEST_HELP=true

	for f in ${RH_FUNCTIONS[@]}
	do
		# if the command has help
		if type $f | grep -qzP '{\s+_rh_try_ret_help '
		then
			echo -e "\t$f - "$($f)
		fi
	done
}

############################## Application area ################################


lxe_launch_helper()
{
	# Collection available commands

	RH_FUNCTIONS=()

	for func in `typeset -F | grep -Po '(?<=-f).*$' | sort`
	do
		RH_FUNCTIONS+=($func);
	done

	# print help if nothing specified

	if [ $# '<' '1' ]
	then
		help
		exit 1
	fi

	# run command
	for f in ${RH_FUNCTIONS[@]}
	do
		if [ "$1" "=" "$f" ]
		then
			$f "${@:2}"
			exit $?
		fi
	done

	echo "Helper function $1 not found, so now printing help..."
	help
	exit 1
}

hd()
{
	# Run helmsdeep. For internal use
	(lxe_launch_helper "$@")
}

hammerhand()
{
	# Run helmsdeep. For internal use
	(lxe_launch_helper "$@")
}

# call helmsdeep only if directly called, that way you can extend by source ./hammerhand
if [ -z "${HELMSDEEP_PREVENT_RH_CALL}" ]
then
	hd "$@"
fi