ingress:
  enabled: false

studio:
  ingress:
    enabled: false

jwt:
  secret: "SUPER-SECRET-JWT-KEY-REPLACE-ME-NOW-12345"

postgres:
  enabled: true
  dbUser: "supabase_admin"
  dbPass: "HighlySecurePassword99!"
  dbName: "postgres"