# supabase-values.yaml

# Alapértelmezett beépített Ingress-ek kikapcsolása (Traefik-et fogunk használni helyette)
ingress:
  enabled: false

studio:
  ingress:
    enabled: false

# Generálj egy erős, egyedi titkos kulcsot a JWT tokenek aláírásához!
jwt:
  secret: "SUPER-SECRET-JWT-KEY-REPLACE-ME-NOW-12345"

# Adatbázis konfiguráció (Alapértelmezetten a chart indít egy PostgreSQL-t)
postgres:
  enabled: true
  dbUser: "supabase_admin"
  dbPass: "HighlySecurePassword99!"
  dbName: "postgres"