apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipfs-pvc
  namespace: ${NAMESPACE}
spec:
  storageClassName: ${STORAGE_CLASS}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${STORAGE_SIZE}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ipfs-node
  namespace: ${NAMESPACE}
  labels:
    app: ipfs
spec:
  selector:
    matchLabels:
      app: ipfs
  template:
    metadata:
      labels:
        app: ipfs
    spec:
      # TODO extract this block as optional
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"


      containers:
      - name: ipfs
        image: ipfs/kubo:latest
        env:
        - name: IPFS_PATH
          value: /data/ipfs
        ports:
        - name: gateway
          containerPort: 8080
        volumeMounts:
        - name: ipfs-data
          mountPath: /data/ipfs
      volumes:
      - name: ipfs-data
        ephemeral:
          volumeClaimTemplate:
            metadata:
              labels:
                type: ipfs-local-volume
            spec:
              storageClassName: 'local-path'
              accessModes: [ "ReadWriteOnce" ]
              resources:
                requests:
                  storage: ${STORAGE_SIZE}
---
apiVersion: v1
kind: Service
metadata:
  name: ipfs-service
  namespace: ${NAMESPACE}
spec:
  internalTrafficPolicy: Local
  selector:
    app: ipfs
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

